command /discord [<string>]:
	trigger:
		send formatted "%{-server::color::discord}%&l|"
		send formatted "%{-server::color::discord}%&l| &fConnect with us via discord @ <tooltip:%{-server::color::discord}%Click here><link:https://%{-server::name::discord}%>%{-server::color::discord}%%{-server::name::discord}%&f!"
		send formatted "%{-server::color::discord}%&l|"
		play sound "block.note_block.chime" to player